./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois100.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois20.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois21.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois22.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois23.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois24.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois25.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois26.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois27.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois28.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois29.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois30.cnf
./gomisat ./testdata/satlib/unsat-dimacs-dubois/dubois50.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-1_6-no-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-1_6-no-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-1_6-no-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-1_6-no-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-1_6-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-1_6-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-1_6-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-1_6-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-2_0-no-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-2_0-no-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-2_0-no-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-2_0-no-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-2_0-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-2_0-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-2_0-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-2_0-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-3_4-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-3_4-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-3_4-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-3_4-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-6_0-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-6_0-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-6_0-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-100-6_0-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-1_6-no-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-1_6-no-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-1_6-no-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-1_6-no-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-1_6-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-1_6-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-1_6-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-1_6-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-2_0-no-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-2_0-no-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-2_0-no-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-2_0-no-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-2_0-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-2_0-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-2_0-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-2_0-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-3_4-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-3_4-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-3_4-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-3_4-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-6_0-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-6_0-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-6_0-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-200-6_0-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-1_6-no-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-1_6-no-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-1_6-no-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-1_6-no-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-1_6-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-1_6-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-1_6-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-1_6-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-2_0-no-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-2_0-no-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-2_0-no-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-2_0-no-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-2_0-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-2_0-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-2_0-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-2_0-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-3_4-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-3_4-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-3_4-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-3_4-yes1-4.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-6_0-yes1-1.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-6_0-yes1-2.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-6_0-yes1-3.cnf
./gomisat ./testdata/satlib/file-dimacs-aim/aim-50-6_0-yes1-4.cnf