package gomisat

import "math/big"

// A Study answers a sequence of weighted counting queries over one formula,
// keeping the component cache between them.
//
// This is the machinery phase 5 is about. A reliability study is not one counting
// question: it walks through thresholds, k-out-of-n bounds, configurations, mission
// phases, or conditions on components having failed. Each query differs from the
// last by a change generated by a known rule, and the sub-problems the searches
// visit overlap heavily.
//
// The queries are expressed as assumptions rather than as edits to the formula. A
// design alternative gets a selector variable, and a query fixes the selectors; a
// conditional reliability fixes the component literal it conditions on. The formula
// itself never changes, which is what makes the cache reusable:
//
// A cache entry says "this set of clauses, with these variables still unassigned,
// has this weighted count". That is true independently of the rest of the formula.
// Clauses outside the component cannot affect it: a satisfied clause cannot
// propagate, and an unsatisfied one outside the component shares no unassigned
// variable with it, so it cannot propagate into it either. So an entry computed
// during one query stays valid for the next, and reuse happens exactly where the
// two searches meet the same sub-problem.
//
// Two things would break that and are therefore not allowed here. Clause
// references must keep their meaning, which holds because counting neither learns
// nor deletes clauses. And the weights must not change: a cached value is a
// weighted count, so a study whose weights move -- the time-dependent case, where
// only the probabilities vary -- needs a new cache, and that case is better served
// by compiling once and re-evaluating, as DESIGN.md says.
type Study struct {
	s       *Solver
	options *SolverOptions
	copt    *CountOptions
	weights *Weights
	cache   map[cacheKey]*big.Float
	counter *weightedCounter

	queries uint64
	total   CountStats
}

// NewStudy prepares a sequence of queries over the solver's clauses.
func NewStudy(s *Solver, options *SolverOptions, copt *CountOptions, weights *Weights) *Study {
	if copt == nil {
		copt = DefaultCountOptions()
	}
	if weights == nil {
		weights = NewWeights(s.NumVars())
	}
	return &Study{
		s:       s,
		options: options,
		copt:    copt,
		weights: weights,
		cache:   make(map[cacheKey]*big.Float),
	}
}

// Count answers one query: the weighted count of the models in which every
// assumption holds. The weight of an assumption literal is part of the answer, so
// conditioning on a component having failed gives the joint probability; divide by
// the probability of the condition to get the conditional one.
func (st *Study) Count(assumptions ...Lit) (*big.Float, CountStats) {
	s := st.s
	level := s.decisionLevel()
	if len(assumptions) > 0 {
		s.newDecisionLevel()
		for _, p := range assumptions {
			if s.LitValue(p) == LFalse {
				// The assumptions contradict the formula or each other.
				s.cancelUntil(level, st.options)
				st.queries++
				return new(big.Float), CountStats{}
			}
			if s.LitValue(p) == LTrue {
				continue
			}
			s.UncheckedEnqueue(p, CRefUndef)
		}
	}

	if st.counter == nil {
		st.counter = newWeightedCounter(s, st.options, st.copt, st.weights, st.cache)
	}
	value, stats := st.counter.count1()
	s.cancelUntil(level, st.options)

	st.queries++
	st.total.Decisions += stats.Decisions
	st.total.Conflicts += stats.Conflicts
	st.total.CacheHits += stats.CacheHits
	st.total.CacheMiss += stats.CacheMiss
	st.total.Components += stats.Components
	st.total.CacheSize = len(st.cache)
	return value, stats
}

// Queries is how many queries have been answered.
func (st *Study) Queries() uint64 { return st.queries }

// Totals are the statistics accumulated over every query, with CacheSize the
// current number of entries.
func (st *Study) Totals() CountStats { return st.total }

// ClearCache drops the memoised components. It is what a study has to do when the
// weights change, since a cached value is a weighted count.
func (st *Study) ClearCache() {
	st.cache = make(map[cacheKey]*big.Float)
	if st.counter != nil {
		st.counter.cache = st.cache
	}
}
