// Package reliability builds the Boolean structure functions of coherent systems
// and encodes them to CNF for model counting.
//
// The point of the package is the query sequences of DESIGN.md phase 5: a
// reliability study does not ask one counting question but a series of them, each
// differing from the last by a change generated by a known rule -- a state
// threshold, a k-out-of-n bound, a configuration, a mission phase. Building the
// formulas here rather than by hand is what makes that difference describable.
//
// Every encoding is counting-safe: an auxiliary variable introduced for a gate is
// defined in both directions, so each assignment of the basic events extends to
// exactly one assignment of the auxiliaries, and the number of models of the CNF
// equals the number of event assignments that satisfy the structure function.
// Getting this wrong is the classic way to inflate a weighted model count, so
// TestEncodingPreservesCount checks it against a direct evaluation.
//
// # Building a system
//
//	m := reliability.New()
//	pumps := m.Events("pump", 3)
//	for _, p := range pumps {
//		m.SetProbability(p, 0.95)
//	}
//	m.Assert(m.AtLeast(2, pumps...)) // two of the three must work
//
//	fmt.Println(m.Reliability())     // 0.992750
//
// [Model.Events] adds components that either work or fail, [Model.And],
// [Model.Or] and [Model.AtLeast] combine them into a structure function, and
// [Model.Assert] states that the system works. [Model.Reliability] is then the
// weighted model count of that function, which is the probability that it holds.
//
// # Components with several states
//
//	levels := m.MultiStateOneHot("valve", 4)          // states 0 to 3
//	m.SetStateProbabilities(levels, []float64{0.05, 0.15, 0.3, 0.5})
//	working := m.AtLeastState(levels, 2)              // state 2 or better
//
// There are two encodings of a multi-state component and the choice is not free.
// [Model.MultiStateOneHot] uses one indicator per state with an exactly-one
// constraint, and it is the one to use with probabilities. [Model.MultiState] uses
// the order encoding, one variable per level meaning "this state or better", which
// makes a threshold a single literal and is convenient when the thresholds are what
// a study varies -- but it cannot carry a state distribution on independent literal
// weights, and [Model.SetStateProbabilities] therefore belongs to the one-hot form.
// DESIGN.md explains why, with the wrong answer that taught it.
//
// # Encodings of the same function
//
// [Model.AtLeast] and [Model.AtLeastSequential] both state "at least k of these",
// and both preserve the model count, but they cost very differently to count: on an
// importance analysis over 36 multi-state components the balanced encoding needed a
// fifth of the work per query and a fifth of the cache. AtLeast is the balanced one
// and the default; the other is kept because it is the other arm of that
// measurement. cmd/gomiencode compares both against stating the same system as a
// linear constraint in [github.com/rellab/gomisat/pkg/csp], which is cheaper again.
package reliability
