// Package reliability builds the Boolean structure functions of coherent systems
// and encodes them to CNF for model counting.
//
// The point of the package is the query sequences of DESIGN.md phase 5: a
// reliability study does not ask one counting question but a series of them, each
// differing from the last by a change generated by a known rule -- a state
// threshold, a k-out-of-n bound, a configuration, a mission phase. Building the
// formulas here rather than by hand is what makes that difference describable.
//
// Every encoding is counting-safe: an auxiliary variable introduced for a gate is
// defined in both directions, so each assignment of the basic events extends to
// exactly one assignment of the auxiliaries, and the number of models of the CNF
// equals the number of event assignments that satisfy the structure function.
// Getting this wrong is the classic way to inflate a weighted model count, so
// TestEncodingPreservesCount checks it against a direct evaluation.
package reliability

import "fmt"

// Node is a literal: a variable of the encoding, possibly negated.
type Node int64

// Not returns the negation of a node. It costs nothing: negation is a sign, not a
// gate.
func (n Node) Not() Node { return -n }

// Model is a system under construction.
type Model struct {
	names    []string // variable i is names[i-1]
	isEvent  []bool   // whether variable i+1 is a basic event or a state level
	events   int      // how many of them there are
	clauses  [][]int64
	trueNode Node
}

// New returns an empty model.
func New() *Model {
	return &Model{names: make([]string, 0, 32)}
}

func (m *Model) newVar(name string, event bool) Node {
	m.names = append(m.names, name)
	m.isEvent = append(m.isEvent, event)
	if event {
		m.events++
	}
	return Node(len(m.names))
}

// Event adds a basic event: a component that is either working or failed. Events
// and gates may be added in any order, which is what lets a system be built one
// subsystem at a time.
func (m *Model) Event(name string) Node {
	return m.newVar(name, true)
}

// Events adds count basic events named name0, name1 and so on.
func (m *Model) Events(name string, count int) []Node {
	out := make([]Node, 0, count)
	for i := 0; i < count; i++ {
		out = append(out, m.Event(fmt.Sprintf("%s%d", name, i)))
	}
	return out
}

// MultiState adds a component with the given number of states, encoded in order:
// the returned node j is "the component is in state j or better", for j from 1 to
// states-1. The chain clauses make the encoding one-to-one with the states, so
// counting over these variables counts states rather than bit patterns.
//
// State 0 is the worst state and needs no variable: it is the case where every
// returned node is false.
func (m *Model) MultiState(name string, states int) []Node {
	if states < 2 {
		panic("reliability: a component needs at least two states")
	}
	levels := make([]Node, 0, states-1)
	for j := 1; j < states; j++ {
		levels = append(levels, m.Event(fmt.Sprintf("%s>=%d", name, j)))
	}
	// Being in state j or better implies being in state j-1 or better.
	for j := 1; j < len(levels); j++ {
		m.clause(-int64(levels[j]), int64(levels[j-1]))
	}
	return levels
}

func (m *Model) clause(lits ...int64) {
	c := make([]int64, len(lits))
	copy(c, lits)
	m.clauses = append(m.clauses, c)
}

// And returns a node that is true exactly when every input is.
func (m *Model) And(inputs ...Node) Node {
	switch len(inputs) {
	case 0:
		return m.True()
	case 1:
		return inputs[0]
	}
	g := m.newVar(fmt.Sprintf("and%d", len(m.names)+1), false)
	long := make([]int64, 0, len(inputs)+1)
	long = append(long, int64(g))
	for _, in := range inputs {
		m.clause(-int64(g), int64(in)) // g -> in
		long = append(long, -int64(in))
	}
	m.clause(long...) // all inputs -> g
	return g
}

// Or returns a node that is true exactly when some input is.
func (m *Model) Or(inputs ...Node) Node {
	switch len(inputs) {
	case 0:
		return m.False()
	case 1:
		return inputs[0]
	}
	g := m.newVar(fmt.Sprintf("or%d", len(m.names)+1), false)
	long := make([]int64, 0, len(inputs)+1)
	long = append(long, -int64(g))
	for _, in := range inputs {
		m.clause(int64(g), -int64(in)) // in -> g
		long = append(long, int64(in))
	}
	m.clause(long...) // g -> some input
	return g
}

// AtLeast returns a node that is true exactly when at least k of the inputs are.
// It is built from And and Or gates, so it is counting-safe for the same reason
// they are.
//
// This is the k-out-of-n system, and k is what a design study varies.
func (m *Model) AtLeast(k int, inputs ...Node) Node {
	n := len(inputs)
	switch {
	case k <= 0:
		return m.True()
	case k > n:
		return m.False()
	case k == n:
		return m.And(inputs...)
	case k == 1:
		return m.Or(inputs...)
	}
	// atLeast[i][j] is "at least j of inputs[i:]", built from the tail up.
	//   atLeast(i, j) = (inputs[i] and atLeast(i+1, j-1)) or atLeast(i+1, j)
	memo := make(map[[2]int]Node, n*k)
	var build func(i, j int) Node
	build = func(i, j int) Node {
		if j <= 0 {
			return m.True()
		}
		if n-i < j {
			return m.False()
		}
		key := [2]int{i, j}
		if got, ok := memo[key]; ok {
			return got
		}
		with := m.And(inputs[i], build(i+1, j-1))
		without := build(i+1, j)
		g := m.Or(with, without)
		memo[key] = g
		return g
	}
	return build(0, k)
}

// AtMost returns a node that is true exactly when at most k of the inputs are.
func (m *Model) AtMost(k int, inputs ...Node) Node {
	negated := make([]Node, 0, len(inputs))
	for _, in := range inputs {
		negated = append(negated, in.Not())
	}
	return m.AtLeast(len(inputs)-k, negated...)
}

// True and False are constant nodes, backed by a variable fixed by a unit clause.
func (m *Model) True() Node {
	if m.trueNode == 0 {
		m.trueNode = m.newVar("true", false)
		m.clause(int64(m.trueNode))
	}
	return m.trueNode
}

func (m *Model) False() Node { return m.True().Not() }

// Assert constrains a node to be true. Asserting the top node of a fault tree is
// what turns the tree into the question "in how many ways does the system fail".
func (m *Model) Assert(n Node) {
	m.clause(int64(n))
}

// CNF returns the clauses, the total number of variables, and how many of them
// are basic events or state levels rather than gate auxiliaries. Because every
// auxiliary is determined by the events, the count of the CNF equals the count
// over the event variables alone; EventVars says which those are.
func (m *Model) CNF() (clauses [][]int64, numVars, numEvents int) {
	out := make([][]int64, len(m.clauses))
	for i, c := range m.clauses {
		out[i] = append([]int64(nil), c...)
	}
	return out, len(m.names), m.events
}

// Dimacs renders the model in DIMACS CNF format, with the variable names as
// comments so that a generated instance stays readable.
func (m *Model) Dimacs() string {
	clauses, numVars, numEvents := m.CNF()
	var b []byte
	b = append(b, fmt.Sprintf("c generated by pkg/reliability\nc %d events, %d variables\n", numEvents, numVars)...)
	for i, name := range m.names {
		b = append(b, fmt.Sprintf("c v%d %s\n", i+1, name)...)
	}
	b = append(b, fmt.Sprintf("p cnf %d %d\n", numVars, len(clauses))...)
	for _, c := range clauses {
		for _, lit := range c {
			b = append(b, fmt.Sprintf("%d ", lit)...)
		}
		b = append(b, "0\n"...)
	}
	return string(b)
}

// EventVars returns the one-based indices of the variables that are basic events
// or state levels. Weights belong on these; the auxiliaries must carry weight one.
func (m *Model) EventVars() []int {
	out := make([]int, 0, m.events)
	for i, isEvent := range m.isEvent {
		if isEvent {
			out = append(out, i+1)
		}
	}
	return out
}

// Names returns the variable names, index 0 being variable 1.
func (m *Model) Names() []string {
	out := append([]string(nil), m.names...)
	return out
}
